#!/usr/bin/env bash
# create-sfx-windows.sh — Produces a self-extracting jpm launcher for Windows
#
# Usage (from project root after mvn package):
#   packaging/oomph-sfx/create-sfx-windows.sh \
#       target/biz.aQute.jpm.run-4.0.0.jar \
#       target/jre-image \
#       target/jpm-windows-amd64.bat \
#       4.0.0
#
# Arguments:
#   jar-file    Path to biz.aQute.jpm.run-*.jar (fat JAR from Maven)
#   jre-dir     Path to the Temurin JRE image directory
#   output-file Destination path for the generated .bat file
#   version     Version string embedded in the .bat (default: 4.0.0)
#
# The output is a self-contained .bat file that:
#   1. Checks for a cached extraction in %LOCALAPPDATA%\jpm-sfx\<version>.
#   2. If not found, decodes the embedded base64 ZIP payload and extracts it.
#   3. Runs  <cache>\jre\bin\java.exe -jar <cache>\jpm.jar  with all args.
#
# The payload ZIP is base64-encoded and appended after the __PAYLOAD__ marker,
# following the same "stub + appended payload" concept as the Oomph installer.
# Decoding on the target machine uses PowerShell 5.1+ (built into Windows 7+).
#
# Requires on the build machine: bash, zip, base64 (all standard on Ubuntu).

set -euo pipefail

JAR_FILE="${1:?Usage: $0 <jar-file> <jre-dir> <output-file> [version]}"
JRE_DIR="${2:?Usage: $0 <jar-file> <jre-dir> <output-file> [version]}"
OUTPUT_FILE="${3:?Usage: $0 <jar-file> <jre-dir> <output-file> [version]}"
VERSION="${4:-4.0.0}"

# ── Validate inputs ────────────────────────────────────────────────────────
[ -f "$JAR_FILE" ] || { echo "ERROR: JAR not found: $JAR_FILE" >&2; exit 1; }
[ -d "$JRE_DIR" ]  || { echo "ERROR: JRE dir not found: $JRE_DIR" >&2; exit 1; }

# ── Build payload ZIP in a temp staging directory ──────────────────────────
STAGING=$(mktemp -d)
trap 'rm -rf "$STAGING"' EXIT

echo "==> Staging payload ..."
cp "$JAR_FILE" "$STAGING/jpm.jar"
cp -r "$JRE_DIR" "$STAGING/jre"

echo "==> Creating ZIP payload ..."
ZIP_FILE="$STAGING/payload.zip"
# Use relative paths inside the ZIP so it extracts as jpm.jar and jre/
(cd "$STAGING" && zip -qr "$ZIP_FILE" jpm.jar jre)

PAYLOAD_SIZE=$(du -sh "$ZIP_FILE" | cut -f1)
echo "    Payload size: $PAYLOAD_SIZE (compressed)"

# ── Base64-encode the ZIP ──────────────────────────────────────────────────
# GNU coreutils base64 wraps at 76 chars by default; other implementations may
# vary, but the Windows decoder strips all CR/LF before decoding anyway.
ENCODED=$(base64 "$ZIP_FILE")

# ── Write the self-extracting .bat ─────────────────────────────────────────
echo "==> Writing $OUTPUT_FILE ..."

# The batch stub uses PowerShell (always available on Win 7+) to decode
# and unzip the payload stored after the __PAYLOAD__ marker in this file.
# CRLF line endings are required for cmd.exe compatibility; printf '\r\n' is
# used for the header lines.  The base64 lines themselves may use LF — the
# PowerShell decoder strips both CR and LF before decoding.
{
  printf '@echo off\r\n'
  printf ':: jpm - Self-extracting launcher for Windows\r\n'
  printf ':: Generated by create-sfx-windows.sh (Oomph SFX pattern)\r\n'
  printf '::\r\n'
  printf ':: Extracts the embedded JRE + jpm.jar on first run, then caches them in\r\n'
  printf '::   %%%%LOCALAPPDATA%%%%\\jpm-sfx\\%s  so subsequent launches are instant.\r\n' "$VERSION"
  printf '\r\n'
  printf 'setlocal enabledelayedexpansion\r\n'
  printf '\r\n'
  printf 'set "CACHE_DIR=%%LOCALAPPDATA%%\\jpm-sfx\\%s"\r\n' "$VERSION"
  printf 'set "JPM_JAR=%%CACHE_DIR%%\\jpm.jar"\r\n'
  printf 'set "JAVA_EXE=%%CACHE_DIR%%\\jre\\bin\\java.exe"\r\n'
  printf '\r\n'
  printf ':: Fast path: already extracted\r\n'
  printf 'if exist "%%JAVA_EXE%%" goto :run\r\n'
  printf '\r\n'
  printf ':: -- Extract ------------------------------------------------------------------\r\n'
  printf 'echo Extracting jpm %s ...\r\n' "$VERSION"
  printf 'if not exist "%%CACHE_DIR%%" mkdir "%%CACHE_DIR%%"\r\n'
  printf '\r\n'
  printf ':: Collect base64 lines from this file (after __PAYLOAD__ marker)\r\n'
  printf 'set "TMP_B64=%%TEMP%%\\jpm-payload-%%RANDOM%%.b64"\r\n'
  printf 'set "TMP_ZIP=%%TEMP%%\\jpm-payload-%%RANDOM%%.zip"\r\n'
  printf 'set "IN_PAYLOAD=0"\r\n'
  printf 'for /f "usebackq delims=" %%%%L in ("%%~f0") do (\r\n'
  printf '    if "!IN_PAYLOAD!"=="1" (\r\n'
  printf '        echo %%%%L>> "%%TMP_B64%%"\r\n'
  printf '    )\r\n'
  printf '    if "%%%%L"=="__PAYLOAD__" set "IN_PAYLOAD=1"\r\n'
  printf ')\r\n'
  printf '\r\n'
  printf ':: Decode base64 → ZIP using PowerShell\r\n'
  printf 'powershell -NoProfile -Command ^\r\n'
  printf '  "$b64=[System.IO.File]::ReadAllText('"'"'%%TMP_B64%%'"'"').Replace([char]13,'"'"''"'"').Replace([char]10,'"'"''"'"');" ^\r\n'
  printf '  "[System.IO.File]::WriteAllBytes('"'"'%%TMP_ZIP%%'"'"',[System.Convert]::FromBase64String($b64));" ^\r\n'
  printf '  "Add-Type -AssemblyName System.IO.Compression.FileSystem;" ^\r\n'
  printf '  "[System.IO.Compression.ZipFile]::ExtractToDirectory('"'"'%%TMP_ZIP%%'"'"','"'"'%%CACHE_DIR%%'"'"')"\r\n'
  printf '\r\n'
  printf 'del "%%TMP_B64%%" 2>nul\r\n'
  printf 'del "%%TMP_ZIP%%" 2>nul\r\n'
  printf '\r\n'
  printf 'if not exist "%%JAVA_EXE%%" (\r\n'
  printf '    echo ERROR: Extraction failed. 1>&2\r\n'
  printf '    exit /b 1\r\n'
  printf ')\r\n'
  printf '\r\n'
  printf ':run\r\n'
  printf '"%%JAVA_EXE%%" -jar "%%JPM_JAR%%" %%*\r\n'
  printf 'exit /b %%ERRORLEVEL%%\r\n'
  printf '\r\n'
  printf '__PAYLOAD__\r\n'
  # %s passes $ENCODED as a literal argument — base64 only uses [A-Za-z0-9+/=\n]
  # so there are no printf format specifiers or backslash sequences to worry about.
  printf '%s\r\n' "$ENCODED"
} > "$OUTPUT_FILE"

TOTAL_SIZE=$(du -sh "$OUTPUT_FILE" | cut -f1)
echo "==> Done: $OUTPUT_FILE ($TOTAL_SIZE)"
