# create-sfx-windows.ps1 — Produces a self-extracting jpm launcher for Windows
#
# Usage (from project root after mvn package and jlink):
#   pwsh -File packaging\oomph-sfx\create-sfx-windows.ps1 `
#        -JarFile  target\biz.aQute.jpm.run-4.0.0-SNAPSHOT.jar `
#        -JreDir   target\jre-image `
#        -OutFile  target\jpm-windows-amd64.bat
#
# The output is a self-contained .bat file that:
#   1. Checks for a cached extraction in %LOCALAPPDATA%\jpm-sfx\<version>.
#   2. If not found, extracts the embedded ZIP payload to that directory.
#   3. Runs  <cache>\jre\bin\java.exe -jar <cache>\jpm.jar  with all args.
#
# The payload ZIP is embedded as a base64-encoded block inside the .bat, using
# the same "stub + appended payload" concept as the Oomph installer — here
# adapted for Windows batch scripting and .NET's built-in ZipFile support.
#
# No external tools (7-Zip, WiX, etc.) are required on either the build or
# target machine.  PowerShell 5.1+ and .NET Framework 4.5+ are present on
# every supported Windows version (7 SP1 onwards).

param(
    [Parameter(Mandatory)][string] $JarFile,
    [Parameter(Mandatory)][string] $JreDir,
    [Parameter(Mandatory)][string] $OutFile,
    [string] $Version = "4.0.0"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Validate inputs ────────────────────────────────────────────────────────
if (-not (Test-Path $JarFile)) { throw "JAR not found: $JarFile" }
if (-not (Test-Path $JreDir))  { throw "JRE dir not found: $JreDir" }

# ── Build payload ZIP ──────────────────────────────────────────────────────
$staging  = Join-Path ([System.IO.Path]::GetTempPath()) "jpm-sfx-$([System.IO.Path]::GetRandomFileName())"
$zipPath  = Join-Path ([System.IO.Path]::GetTempPath()) "jpm-payload-$([System.IO.Path]::GetRandomFileName()).zip"
try {
    New-Item -ItemType Directory -Path $staging | Out-Null
    Copy-Item $JarFile (Join-Path $staging "jpm.jar")
    Copy-Item -Recurse $JreDir (Join-Path $staging "jre")

    Write-Host "==> Creating ZIP payload ..."
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory($staging, $zipPath)
    $payloadSize = (Get-Item $zipPath).Length / 1MB
    Write-Host ("    Payload size: {0:N1} MB" -f $payloadSize)

    # ── Base64-encode the ZIP ──────────────────────────────────────────────
    $bytes  = [System.IO.File]::ReadAllBytes($zipPath)
    $b64    = [System.Convert]::ToBase64String($bytes)

    # Split into 76-char lines so the .bat file stays readable and avoids
    # the 8191-character cmd.exe line-length limit.
    $lines = [System.Collections.Generic.List[string]]::new()
    for ($i = 0; $i -lt $b64.Length; $i += 76) {
        $chunk = $b64.Substring($i, [Math]::Min(76, $b64.Length - $i))
        $lines.Add($chunk)
    }
    $encodedPayload = $lines -join "`r`n"

    # ── Write the self-extracting .bat ────────────────────────────────────
    Write-Host "==> Writing $OutFile ..."

    # The batch stub uses PowerShell (always available on Win 7+) to decode
    # and unzip the payload stored after the __PAYLOAD__ marker in this file.
    $stub = @"
@echo off
:: jpm - Self-extracting launcher for Windows
:: Generated by create-sfx-windows.ps1 (Oomph SFX pattern)
::
:: Extracts the embedded JRE + jpm.jar on first run, then caches them in
:: %%LOCALAPPDATA%%\jpm-sfx\$Version so subsequent launches are instant.

setlocal enabledelayedexpansion

set "CACHE_DIR=%LOCALAPPDATA%\jpm-sfx\$Version"
set "JPM_JAR=%CACHE_DIR%\jpm.jar"
set "JAVA_EXE=%CACHE_DIR%\jre\bin\java.exe"

:: Fast path: already extracted
if exist "%JAVA_EXE%" goto :run

:: ── Extract ──────────────────────────────────────────────────────────────
echo Extracting jpm $Version ...
if not exist "%CACHE_DIR%" mkdir "%CACHE_DIR%"

:: Collect base64 lines from this file (after __PAYLOAD__ marker)
set "TMP_B64=%TEMP%\jpm-payload-%RANDOM%.b64"
set "TMP_ZIP=%TEMP%\jpm-payload-%RANDOM%.zip"
set "IN_PAYLOAD=0"
for /f "usebackq delims=" %%L in ("%~f0") do (
    if "!IN_PAYLOAD!"=="1" (
        echo %%L>> "%TMP_B64%"
    )
    if "%%L"=="__PAYLOAD__" set "IN_PAYLOAD=1"
)

:: Decode base64 → ZIP using PowerShell
powershell -NoProfile -Command ^
  "$b64=[System.IO.File]::ReadAllText('%TMP_B64%').Replace([char]13,'').Replace([char]10,'');" ^
  "[System.IO.File]::WriteAllBytes('%TMP_ZIP%',[System.Convert]::FromBase64String($b64));" ^
  "Add-Type -AssemblyName System.IO.Compression.FileSystem;" ^
  "[System.IO.Compression.ZipFile]::ExtractToDirectory('%TMP_ZIP%','%CACHE_DIR%')"

del "%TMP_B64%" 2>nul
del "%TMP_ZIP%" 2>nul

if not exist "%JAVA_EXE%" (
    echo ERROR: Extraction failed. 1>&2
    exit /b 1
)

:run
"%JAVA_EXE%" -jar "%JPM_JAR%" %*
exit /b %ERRORLEVEL%

__PAYLOAD__
"@

    # Write stub + payload in one shot (UTF-8 without BOM for cmd.exe compat)
    $encoding = New-Object System.Text.UTF8Encoding $false
    $content  = $stub + $encodedPayload + "`r`n"
    [System.IO.File]::WriteAllText($OutFile, $content, $encoding)

    $totalSize = (Get-Item $OutFile).Length / 1MB
    Write-Host ("==> Done: $OutFile ({0:N1} MB)" -f $totalSize)
}
finally {
    Remove-Item -Recurse -Force $staging -ErrorAction SilentlyContinue
    Remove-Item -Force $zipPath -ErrorAction SilentlyContinue
}
