#!/bin/sh
# jpm — Self-extracting launcher (Unix)
#
# This script is generated by create-sfx-unix.sh.  It contains the payload
# (jlink JRE + jpm.jar) appended as a raw payload.tar.gz after the
# __PAYLOAD__ marker line.
# On first run it extracts to a per-invocation temp directory, runs jpm, then
# cleans up automatically.
#
# This pattern is inspired by the Eclipse Oomph self-extracting installer:
#   https://github.com/eclipse-oomph/oomph
# The Oomph installer prepends a native C launcher stub to a ZIP archive; this
# shell-script variant achieves the same result without requiring a pre-built
# native binary, making it easy to produce from any Unix CI node.
#
# ── Runtime behaviour ──────────────────────────────────────────────────────
#   1. Locate the __PAYLOAD__ marker in this file.
#   2. Pipe everything after the marker directly to tar -xz.
#   3. Execute  <tmpdir>/jre/bin/java -jar <tmpdir>/jpm.jar  with all args.
#   4. Trap EXIT/INT/TERM to delete the tmpdir.
#
# The payload layout inside the tarball:
#   jre/   — jlink-created minimal JRE (java.base + logging + xml + …)
#   jpm.jar — fat JAR produced by Maven

set -e

# ── Locate the payload inside this script ─────────────────────────────────
SELF=$(cd "$(dirname "$0")" && pwd)/$(basename "$0")
PAYLOAD_LINE=$(awk '/^__PAYLOAD__/{print NR+1; exit}' "$SELF")

if [ -z "$PAYLOAD_LINE" ]; then
    echo "ERROR: __PAYLOAD__ marker not found — this script may be incomplete." >&2
    exit 1
fi

# ── Create temp directory and register cleanup ─────────────────────────────
JPM_TMP=$(mktemp -d "${TMPDIR:-/tmp}/jpm.XXXXXXXXXX")
# shellcheck disable=SC2064
trap "rm -rf '$JPM_TMP'" EXIT INT TERM HUP

# ── Extract the bundled JRE + JAR ─────────────────────────────────────────
tail -n +"$PAYLOAD_LINE" "$SELF" | tar -xz -C "$JPM_TMP"

# ── Run jpm ───────────────────────────────────────────────────────────────
exec "$JPM_TMP/jre/bin/java" -jar "$JPM_TMP/jpm.jar" "$@"

# (Execution never reaches here; exec replaces the shell process.)
__PAYLOAD__
